name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.19
        id: go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.19

      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Build
        run: |
          go get -d -v
          go build -v .          